conda activate clues

python3 inference.py --times Quechua_PhasedChr1_no_missing_biallelic_no_EUR_bypop_sampled_CLUES_103614521 --coal Quechua_PhasedChr1_no_missing_biallelic_no_EUR_bypop_CLUES.coal --out Clues/Quechua_PhasedChr1_no_missing_biallelic_no_EUR_bypop_sampled_CLUES_103614521
python plot_traj.py --ext png Clues/Quechua_PhasedChr1_no_missing_biallelic_no_EUR_bypop_sampled_CLUES_103614521 testing_figure/Quechua_PhasedChr1_no_missing_biallelic_no_EUR_bypop_sampled_CLUES_103614521
